# Generated by Django 5.2.3 on 2025-06-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='statut_actuel',
            field=models.CharField(choices=[('en_etude', 'En étude'), ('en_poste', 'En poste'), ('en_stage', 'En stage'), ('en_recherche', "En recherche d'emploi"), ('autre', 'Autre')], max_length=20),
        ),
    ]
