# Generated by Django 5.2.3 on 2025-06-13 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alter_etudiant_statut_actuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplome',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes', to='alumni.etudiant'),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='intitule',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='specialisation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='universite',
            field=models.CharField(max_length=100),
        ),
    ]
